#! /bin/bash
#
#
chmod +x /etc/fsl/5.0/fsl.sh
source /etc/fsl/5.0/fsl.sh

for input_path in /cb_norm_damage/input/*
do
    output_path=${input_path/input/output}
    ./run_single.sh ${input_path} ${output_path}
done

echo "Done!"